stages:
  - analyze
  - test
  - package
variables:
  GIT_SSL_NO_VERIFY: "true"
Analyze:
  stage: analyze
  script:
   - .\build.ps1 -Task "Analyze"
  tags:
    - powershell
Test:
  stage: test
  script:
   - .\build.ps1 -Task "Test"
  tags:
    - powershell
    - pester
Package:
  stage: package
  artifacts:
   paths:
    - src/*