stages:
  - analyze
  - test
  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
Analyze:
  stage: analyze
  script:
   - .\build.ps1 -Task "Analysis"
  tags:
    - powershell
Test:
  stage: test
  script:
   - .\build.ps1 -Task "Test"
  tags:
    - powershell
Release:
  stage: release
  script:
   - .\build.ps1 -Task "Release"
  only:
    - master
  tags:
    - powershell