stages:
  - test
  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
Check:
  stage: test
  script:
   - .\build.ps1 -Task "Test"
  except:
   - master
  tags:
    - powershell
Release:
  stage: release
  script:
   - .\build.ps1 -Task "Release"
  only:
    - master
  tags:
    - powershell