stages:
  - test
  - package
variables:
  GIT_SSL_NO_VERIFY: "true"
Test:
  stage: test
  script:
   - Invoke-Pester -EnableExit
  tags:
    - powershell
    - pester
Package:
  stage: package
  artifacts:
   paths:
    - src/*