stages:
  - check
  - release
variables:
  GIT_SSL_NO_VERIFY: "true"
Check:
  stage: check
  script:
   - .\build.ps1 -Task "Check"
  except:
   - master
  tags:
    - powershell
Release:
  stage: release
  script:
   - .\build.ps1 -Task "Release"
  only:
    - master
  tags:
    - powershell