stages:
  - analyze
  - test
  - release
  - deploy
variables:
  GIT_SSL_NO_VERIFY: "true"
analyze:
  stage: analyze
  script:
   - .\build.ps1 -Tasks 'analyze'
  tags:
    - powershell
test:
  stage: test
  script:
   - .\build.ps1 -Tasks 'test'
  tags:
    - powershell
release:
  stage: release
  script: ls
  artifacts:
    paths:
    - src
  tags:
    - powershell    
deploy:
  stage: deploy
  script:
   - .\build.ps1 -Tasks 'release'
  only:
    - master
  tags:
    - powershell
  when: manual